FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y \
    nmap \
    hping3 \
    hydra \
    netcat-traditional \
    python3 \
    python3-pip \
    python3-scapy \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /attacks
CMD ["/bin/bash"]
